version: '3.6'

services: 
  node: 
    container_name: node_container
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8081:8081"
    volumes:
      - ./src:/app/src